<?php Load::lib("html") ?>
<?php Load::lib("formulario") ?>

<?php $titulo = "Consultar Producto" ?>
<?php $subtitulo = "A continuación se muestra la información del producto." ?>
<?php $modelo = "Producto"; ?>

<?= isset($msg) ? View::partial("mensajes", false, array("mensaje" => $mensaje, "msg" => $msg) ) : "" ?>

<table style="width: 100%" cellpadding="0" cellspacing="0">
	<tr>
		<td class="panel_gris" style="width: 80%">
			<div style="float: left;">
		    	<div class="titulo"><?= $titulo ?></div>
		        <div class="subtitulo"><?= $subtitulo ?></div>
		    </div>
		    <div style="float: right;">
		    	<table>
		    		<tr>
		    			<td>
		    				<?php
                        		if(Session::get("filtro")){
                        			$filtro = "/".Session::get("filtro")."/".Session::get("campo")."-".Session::get("orden")."/".Session::get("pagina");
									
									if(Session::get("unico")){
                        				$filtro = "";
										Session::set("unico",false);
                        			}
                        		}
								else{
									$filtro = "";
								}
                        	?>
		    				<?= Html::linkAjax($controller_name."/reporte".$filtro,"REGRESAR","principal","id: boton2") ?>
		           		</td>
		    		</tr>
		    	</table>
		    </div>
    	</td>
	</tr>
	<tr>
		<td class="panel_azul">
			<?= Formulario::inicioAjax($controller_name."/modificar","principal") ?>
		    <?= Formulario::oculto("id",$producto -> id) ?>
		    <table border="0" cellpadding="1" cellspacing="1" style="width: 100%">
		    	<tr>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td>
		    			<?= Formulario::titulo("Información del Producto",false) ?>
		                <?= Formulario::mayusculas("codigo",$producto -> codigo,"class: tchico","disabled: disabled;") ?>
		                <?= Formulario::subtitulo("Código",false) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::titulo("",false) ?>
		                <?php $categorias = ProductoCategoria::reporte("id>0","nombre ASC"); ?>
		                <?= Formulario::autocompleteModelo("categoria",$categorias,"nombre",$producto -> categoria() -> nombre,"validate: required:true","class: tchico") ?>
		                <?= Formulario::subtitulo("Categoría",true) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<?= Formulario::titulo("Información del Fabricante",false) ?>
		                <?= Formulario::mayusculas("fabricante",$producto -> codigo_fabricante,"class: tchico") ?>
		                <?= Formulario::subtitulo("Código de Fabricante",false) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::titulo("",false) ?>
		                <?php $marcas = ProductoMarca::reporte("id>0","nombre ASC"); ?>
		                <?= Formulario::autocompleteModelo("marca",$marcas,"nombre",$producto -> marca() ? $producto -> marca() -> nombre : "","class: tchico") ?>
		                <?= Formulario::subtitulo("Marca de Fabricante",false) ?>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="3">
		    			<?= Formulario::mayusculas("nombre",$producto -> nombre,"validate: required:true","class: tmediano") ?>
		                <?= Formulario::subtitulo("Nombre",true) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<table>
		    				<tr>
		    					<td>
		    						<?= Formulario::dinero("costo_pesos",$producto -> costo_pesos,"validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td>
		    						<?= Formulario::dinero("costo_pesos_iva",$producto -> costo_pesos * 1.16,"disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Costo en Pesos",true) ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Costo en Pesos + IVA",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<table>
		    				<tr>
		    					<td>
		    						<?= Formulario::dinero("costo_dolares",$producto -> costo_dolares,"validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td>
		    						<?= Formulario::dinero("costo_dolares_iva",$producto -> costo_dolares * 1.16,"disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Costo en Dolares",true) ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Costo en Dolares + IVA",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="3" rowspan="3">
		    			<?= Formulario::textarea("descripcion",$producto -> descripcion,"class: tmediano","style: height: 95px;") ?>
		                <?= Formulario::subtitulo("Descripcion",false) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<?= Formulario::dinero("precio_contado",$producto -> precio_contado,"validate: required:true","class: tchico","style: text-align: center; font-weight: bold; background-color: #EEDDFF;") ?>
		                <?= Formulario::subtitulo("Precio Contado",true) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::dinero("precio_minimo",ceil($producto -> precio_contado * 0.95),"disabled: disabled","validate: required:true","class: tchico","style: text-align: center;") ?>
		                <?= Formulario::subtitulo("Precio Mínimo",false) ?>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<table border="0">
		    				<tr>
		    					<td width="182">
		    						<?php $disponibilidad = $producto -> disponibilidad(1) ?>
									<?= Formulario::select("sucursal",array("1" => "AMECA"),"nombre","id","1","class: schico","style: text-align: center; width: 100%;") ?>			
		    					</td>
		    					<td width="10">
		    						
		    					</td>
		    					<td width="182">
		    						<?= Formulario::numerico("disponibilidad",$disponibilidad,"validate: required:true","class: tchico","style: text-align: center; width: 95%; font-weight: bold; background-color: #EEDDFF;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Sucursal",false) ?>			
		    					</td>
		    					<td width="10">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Disponibilidad",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<table border="0">
		    				<tr>
		    					<td width="182">
		    						<?= Formulario::dinero("pago_mensual",$producto -> precio_credito / 6,"disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 95%;") ?>
		    					</td>
		    					<td width="10">
		    						
		    					</td>
		    					<td width="182">
		    						<?= Formulario::dinero("pago_mensual_12",$producto -> precio_credito12 / 12,"disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 95%;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("6 Meses",false) ?>			
		    					</td>
		    					<td width="10">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("12 Meses",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    	</tr>
		    	<tr>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="6" class="trebuchet">
		    			<i>Los campos con <?= Formulario::asterisco() ?> son obligatorios.</i>
		    		</td>
		    		<td align="right">
		    			<table border="0">
		                    <tr>
		                        <td id="link1">
		                        	<?= Html::linkAjax($controller_name."/reporte".$filtro,"CANCELAR","principal","id: boton2") ?>
		                        </td>
		                        <td>
		                        	<?= Formulario::submit("MODIFICAR","class: boton1","") ?>    
		                        </td>
		                        <td>
		                        	<?php if($producto -> oferta == "SI"){ ?>
		                        		<?= Html::linkAjax($controller_name."/quitarOferta/".$producto -> id,"QUITAR OFERTA","principal","id: boton4") ?>
		                        	<?php } else { ?>
		                        		<?= Html::linkAjax($controller_name."/publicarOferta/".$producto -> id,"PONER EN OFERTA","principal","id: boton3") ?>
		                        	<?php } ?>
		                        </td>
		                    </tr>
		                </table>
		    		</td>
		    	</tr>
		    </table>
		</td>
	</tr>
</table>