<?php Load::lib("html") ?>
<?php Load::lib("formulario") ?>
<?php Load::lib("formato") ?>

<script language="JavaScript">
	document.getElementById("bgeneral").value = "";
</script> 

<?php $titulo = "Inventario de Productos" ?>
<?php $subtitulo = "Los Productos son las mercancias que se ofrecen en la tienda." ?>
<?php $modelo = "Producto"; ?>
<?php 
    $titulos = array(
        "codigo" => "Código|100",
        "categoria_id" => "Categoría|200",
        "marca_id" => "Marca|200",
        "codigo_fabricante" => "Fabricante|200",
        "nombre" => "Nombre|1400",
        "precio_contado" => "Precio|150",
        "disponibilidad" => "Disponibilidad|150",

    );
?> 

<?= isset($msg) ? View::partial("mensajes", false, array("mensaje" => $mensaje, "msg" => $msg) ) : "" ?>

<table style="width: 100%" cellpadding="0" cellspacing="0">
	<tr>
		<td class="panel_azul">
			<div style="float: left;">
		    	<div class="titulo"><?= $titulo ?></div>
		        <div class="subtitulo"><?= $subtitulo ?></div>
		    </div>
		    <div id="inversion" style="float: right;"><?= Html::linkAjax("productos/inversion","Inversión Total","inversion","class: boton2") ?></div>
		</td>
	</tr>
	<tr>
		<td class="panel_gris">
			<table border="0" cellpadding="1" cellspacing="1" style="width: 100%;">
		        <tr>
		            <?php if($titulos) foreach($titulos as $field => $value){ $titulo = substr($value,0,strpos($value,"|")); $tam = substr($value,strpos($value,"|")+1); ?>
		            <th style="width: <?= $tam ?>px;" class="reporte_header">
		                <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1", $titulo,"principal") ?>
		                <?php 
		                    if($campo == $field){
		                        if($orden=="ASC"){
		                            echo Html::linkAjax($controller_name."/inventario/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1",Html::imagen("icons/button_download.png","Ordenar Ascendente",12,12),"principal");
		                        }
		                        else{
		                            echo Html::linkAjax($controller_name."/inventario/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1",Html::imagen("icons/button_upload.png","Ordenar Descendente",12,12),"principal");
		                        }
		                    }
		                ?>
		            </th>
		            <?php } ?>
		            <th colspan="2" width="30" class="reporte_header">
		                
		            </th>
		        </tr>
		        <?php $i=0; if($registros) foreach($registros as $registro){ $i++; ?>
		       	<tr style="height: 20px;">
		            <?php if($titulos) foreach($titulos as $field => $value){ ?>
		            	<?php
		            		switch($field){
								case "codigo": ?><td class="reporte_fila<?= $i ?>" align="center"><?= $registro -> {$field} ?></td><?php break;
								case "marca_id": ?><td class="reporte_fila<?= $i ?>" align="center"><?= $registro -> {$field} > 0 ? ProductoMarca::consultar($registro -> {$field}) -> nombre : "-" ?></td><?php break;
								case "categoria_id": ?><td class="reporte_fila<?= $i ?>" align="center"><?= ProductoCategoria::consultar($registro -> {$field}) -> nombre ?></td><?php break;
								case "precio_contado": ?><td class="reporte_fila<?= $i ?>" align="center"><?= Formato::dinero($registro -> {$field}) ?></td><?php break;
								case "precio_credito": ?><td class="reporte_fila<?= $i ?>" align="center"><?= Formato::dinero($registro -> {$field} / 6) ?></td><?php break;
								case "precio_credito12": ?><td class="reporte_fila<?= $i ?>" align="center"><?= Formato::dinero($registro -> {$field} / 12) ?></td><?php break;
								case "disponibilidad": ?><td class="reporte_fila<?= $i ?>" align="center"><?= $registro -> disponibilidad(Session::get("sucursal")) ?></td><?php break;
								case "codigo_fabricante": ?><td class="reporte_fila<?= $i ?>" align="center"><?= $registro -> {$field} ? $registro -> {$field} : "-" ?></td><?php break;
								default:  ?><td class="reporte_fila<?= $i ?>" align="left"><?= $registro -> {$field} ?></td><?php break;
		            		}
		            	?>
		            <?php } ?>
		            <td class="reporte_fila<?= $i ?>" style="max-width: 30px;">
		            	<?= Html::linkAjax($controller_name."/consulta/".$registro -> id,Html::imagen("miniconos/magnifier.png","Consultar ".$modelo,15,15),"principal") ?>
		            </td>
		            <td class="reporte_fila<?= $i ?>" style="max-width: 30px;">
		            	<?= Html::linkAjaxConfirmado($controller_name."/eliminar/".$registro -> id,Html::imagen("miniconos/delete.png","Eliminar ".$modelo,15,15),"principal","") ?>
		            </td>
		        </tr>
		        <?php if($i>=2) $i=0; } ?>
		        <tr>
		            <th colspan="10" class="reporte_footer">
		                <table border="0" style="width: 100%;">
		                    <tr>
		                        <td style="text-align: left; width: 100%;" class="trebuchet">Total de Registros: <?= $nregistros ?></td>
		                        <?php if($nps>10){ ?>
		                            <?php if($np>=3){ ?>                    
		                            <td class="reporte_paginas">
		                                <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/1","1","principal") ?> 
		                            </td>
		                            <td class="reporte_paginas">
		                                <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/".($np - 2),"...","principal") ?> 
		                            </td>
		                            <?php } ?>                        
		                            <?php for($i=($np>1 ? $np-1 : $np);$i<=($np+1>$nps ? $np : $np+1);$i++){ ?>
		                                <td <?= $i==$np ? 'class="reporte_pagina_actual"' : 'class="reporte_paginas"' ?>>
		                                    <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/".$i,$i,"principal") ?> 
		                                </td>
		                            <?php } ?>
		                            <?php if($i<=$nps){ ?>                        
		                            <td class="reporte_paginas">
		                                <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/".$i,"...","principal") ?>    
		                            </td>
		                            <td class="reporte_paginas">
		                                <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/".$nps,$nps,"principal") ?>    
		                            </td>
		                            <?php } ?>
		                        <?php } else { ?> 
		                            <?php for($i=1;$i<=$nps;$i++){ ?>
		                                <td <?= $i==$np ? 'class="reporte_pagina_actual"' : 'class="reporte_paginas"' ?>>
		                                    <?= Html::linkAjax($controller_name."/inventario/".$filtro."/".$campo."-".($orden=='ASC' ? 'DESC' : 'ASC')."/".$i,$i,"principal") ?> 
		                                </td>
		                            <?php } ?>    
		                        <?php } ?>                   
		                    </tr>
		                </table>
		            </th>
		        </tr>
		    </table>
		</td>
	</tr>
</table>