<?php Load::lib("html") ?>
<?php Load::lib("formulario") ?>

<?php $titulo = "Registrar Producto" ?>
<?php $subtitulo = "Para registrar un nuevo Producto es necesario llenar el siguiente formulario." ?>
<?php $modelo = "Producto"; ?>

<?= isset($msg) ? View::partial("mensajes", false, array("mensaje" => $mensaje, "msg" => $msg) ) : "" ?>

<table style="width: 100%" cellpadding="0" cellspacing="0">
	<tr>
		<td class="panel_gris" style="width: 80%">
			<div style="float: left;">
		    	<div class="titulo"><?= $titulo ?></div>
		        <div class="subtitulo"><?= $subtitulo ?></div>
		    </div>
		    <div style="float: right;">
		    	<table>
		    		<tr>
		    			<td>
		    				<!--
		    					<?= Html::linkAjax($controller_name."/reporte","TODOS LOS PRODUCTOS","principal","id: link_boton1") ?></a>
		    				-->
		           		</td>
		    		</tr>
		    	</table>
		    </div>
    	</td>
	</tr>
	<tr>
		<td class="panel_azul">
			<?= Formulario::inicioAjax($controller_name."/registrar","principal") ?>
		    <?= Formulario::oculto("pais","MÉXICO") ?>
		    <table border="0" cellpadding="1" cellspacing="1" style="width: 100%">
		    	<tr>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td>
		    			<?= Formulario::titulo("Información del Producto",false) ?>
		                <?= Formulario::mayusculas("codigo","","class: tchico","disabled: disabled;") ?>
		                <?= Formulario::subtitulo("Código",false) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::titulo("",false) ?>
		                <?php $categorias = ProductoCategoria::reporte("id>0","nombre ASC"); ?>
		                <?= Formulario::autocompleteModelo("categoria",$categorias,"nombre","","validate: required:true","class: tchico") ?>
		                <?= Formulario::subtitulo("Categoría",true) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<?= Formulario::titulo("Información del Fabricante",false) ?>
		                <?= Formulario::mayusculas("fabricante","","class: tchico") ?>
		                <?= Formulario::subtitulo("Código de Fabricante",false) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::titulo("",false) ?>
		                <?php $marcas = ProductoMarca::reporte("id>0","nombre ASC"); ?>
		                <?= Formulario::autocompleteModelo("marca",$marcas,"nombre","","class: tchico") ?>
		                <?= Formulario::subtitulo("Marca de Fabricante",false) ?>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="3">
		    			<?= Formulario::mayusculas("nombre","","validate: required:true","class: tmediano") ?>
		                <?= Formulario::subtitulo("Nombre",true) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<?= Formulario::dinero("costo_compra","","validate: required:true","class: tchico","style: text-align: center;") ?>
		                <?= Formulario::subtitulo("Costo sin IVA",true) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::select("moneda",array("DOLARES" => "DOLARES", "PESOS" => "PESOS"),"DOLARES","class: schico","style: text-align: center;") ?>
		                <?= Formulario::subtitulo("Moneda",false) ?>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="3" rowspan="3">
		    			<?= Formulario::textarea("descripcion","","class: tmediano","style: height: 95px;") ?>
		                <?= Formulario::subtitulo("Descripcion",false) ?>
		    		</td>
		    		<td style="width: 2.67%"></td>
		    		<td>
		    			<?= Formulario::dinero("precio_minimo","","validate: required:true","class: tchico","style: text-align: center;","disabled: disabled;") ?>
		                <?= Formulario::subtitulo("Precio Mínimo",false) ?>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<?= Formulario::dinero("precio_contado","","validate: required:true","class: tchico","style: text-align: center;","disabled: disabled;") ?>
		                <?= Formulario::subtitulo("Precio Contado",false) ?>
		    		</td>
		    	</tr>
		    	<tr style="height: 10px;">
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td style="width: 2.66%"></td>
		    		<td>
		    			<table>
		    				<tr>
		    					<td>
		    						<?= Formulario::dinero("precio_credito","","disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td>
		    						<?= Formulario::dinero("pago_mensual","","disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Precio Crédito",false) ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Mensualidad",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    		<td style="width: 2.66%"></td>
		    		<td><table>
		    				<tr>
		    					<td>
		    						<?= Formulario::dinero("precio_credito_12","","disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td>
		    						<?= Formulario::dinero("pago_mensual_12","","disabled: disabled","validate: required:true","class: tchico","style: text-align: center; width: 100%;") ?>
		    					</td>
		    				</tr>
		    				<tr>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Precio Crédito",false) ?>			
		    					</td>
		    					<td width="22">
		    						
		    					</td>
		    					<td align="right">
		    						<?= Formulario::subtitulo("Mensualidad",false) ?>		
		    					</td>
		    				</tr>
		    			</table>
		    		</td>
		    	</tr>
		    	<tr>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.67%"></td>
		    		<td style="width: 23%"></td>
		    		<td style="width: 2.66%"></td>
		    		<td style="width: 23%"></td>
		    	</tr>
		    	<tr>
		    		<td colspan="6" class="trebuchet">
		    			<i>Los campos con <?= Formulario::asterisco() ?> son obligatorios.</i>
		    		</td>
		    		<td align="right">
		    			<table border="0">
		                    <tr>
		                        <td id="link1">
		                        	<?= Html::linkAjax($controller_name."/reporte","CANCELAR","principal","id: boton2") ?>
		                        </td>
		                        <td>
		                        	<?= Formulario::submit("REGISTRAR","class: boton1","") ?>    
		                        </td>
		                    </tr>
		                </table>
		    		</td>
		    	</tr>
		    </table>
		</td>
	</tr>
</table>